// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd0upEdgPhkyjAX1VRCy4G22hYjNYCkP4',
    appId: '1:701603368846:web:0cd83d0a61f5a8d5b1dedf',
    messagingSenderId: '701603368846',
    projectId: 'sakinah-7390c',
    authDomain: 'sakinah-7390c.firebaseapp.com',
    storageBucket: 'sakinah-7390c.firebasestorage.app',
    measurementId: 'G-S515LQ1FJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFZt6g5buNFAdZUnE5Y9reg06gAsd2NG4',
    appId: '1:701603368846:android:df1c6940a4d27339b1dedf',
    messagingSenderId: '701603368846',
    projectId: 'sakinah-7390c',
    storageBucket: 'sakinah-7390c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYUHfUqRfVHlyqn5-u762fnHZJg9r9d0',
    appId: '1:701603368846:ios:a67b09cf54d1fe85b1dedf',
    messagingSenderId: '701603368846',
    projectId: 'sakinah-7390c',
    storageBucket: 'sakinah-7390c.firebasestorage.app',
    iosClientId: '701603368846-m59so1tkca5a3hjmq938aq2su9dkinof.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakinah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLYUHfUqRfVHlyqn5-u762fnHZJg9r9d0',
    appId: '1:701603368846:ios:a67b09cf54d1fe85b1dedf',
    messagingSenderId: '701603368846',
    projectId: 'sakinah-7390c',
    storageBucket: 'sakinah-7390c.firebasestorage.app',
    iosClientId: '701603368846-m59so1tkca5a3hjmq938aq2su9dkinof.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakinah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd0upEdgPhkyjAX1VRCy4G22hYjNYCkP4',
    appId: '1:701603368846:web:178e141d5add0b3eb1dedf',
    messagingSenderId: '701603368846',
    projectId: 'sakinah-7390c',
    authDomain: 'sakinah-7390c.firebaseapp.com',
    storageBucket: 'sakinah-7390c.firebasestorage.app',
    measurementId: 'G-753ZH9LN76',
  );
}
