name: sakinah
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.0.1

  image_picker: ^1.0.4
  connectivity_plus: ^7.0.0
  dio: ^5.4.1
  permission_handler: ^11.3.0
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  camera: ^0.12.0+1
  google_mlkit_face_detection: ^0.13.2
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sakina_logo.png
